### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by hanshangjin** [mattragoza/conda-molgrid#1]
![make_error](https://user-images.githubusercontent.com/46646990/147564669-aee6df85-6e7e-4c17-b51f-7c8a4863e26d.PNG)
I had an error when building molgrid with 'make -j8'. Could you tell me how to deal with this issue? Thanks!

**Comment by mattragoza** [comment]
I assume this issue has been resolved through https://github.com/gnina/libmolgrid/issues/81?
